import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {api,COMPANY} from '/home/op/office-continuity/bin/pcapi.mjs';
const dir='/srv/hot-data/energy-markets/app', project='96bbd5b1-94da-4781-8c2b-455fdfb28d1a';
const command='2b6bf987-6800-4d4c-a23a-d470a4bb0ea6', reviewer='0af74a08-cb39-4cf5-a94f-117b242ea08c', worker='2f30b8dd-306b-4735-a135-f8d3127c8c0e';
const spec='PROCUREMENT_RESEARCH_CANONICAL_ENGINEERING_SPEC_v1_1.md', hash='86c4bd4eeb5f9d0ebad94763128b221eb64525a2b7fff1007dab0af88b39cb6c';
const existing=await api('GET',`/companies/${COMPANY}/issues`);
const workspaces=await api('GET',`/projects/${project}/workspaces`);
const workspace=workspaces.find(w=>w.cwd===dir) ?? await api('POST',`/projects/${project}/workspaces`,{name:'Brunode canonical workspace',sourceType:'non_git_path',cwd:dir,isPrimary:true});
await api('PATCH',`/projects/${project}`,{status:'in_progress',description:`Procurement Research v1.1. Sole normative source ${dir}/docs/canonical/${spec}, SHA256 ${hash}. Execute canonical IMP-01..29, typed dependencies and parent receipts per §§20.2,25.1,25.2. Existing Paperclip office, Brunode only. No real purchases/autonomy changes. Full UI later. Owner authorized exclusive focus 2026-09-19.`,executionWorkspacePolicy:{enabled:true,defaultMode:'shared_workspace',sharedWorkspaceConcurrency:'allow',allowIssueOverride:true,defaultProjectWorkspaceId:workspace.id,workspaceStrategy:{type:'project_primary'}}});
const root=existing.find(i=>i.projectId===project && i.title==='Procurement Research v1.1 — ejecución del grafo canónico') ?? await api('POST',`/companies/${COMPANY}/issues`,{title:'Procurement Research v1.1 — ejecución del grafo canónico',description:fs.readFileSync(dir+'/AGENTS.md','utf8'),status:'backlog',priority:'high',projectId:project,projectWorkspaceId:workspace.id});
const parents={};
const lines=fs.readFileSync(dir+'/docs/canonical/'+spec,'utf8').split('\n');
for(const imp of ['IMP-01','IMP-25','IMP-26']){
 const objective=lines.find(l=>l.startsWith(`| ${imp} |`)); const dependencies=lines.find(l=>l.startsWith(`| **${imp}** |`));
 parents[imp]=existing.find(i=>i.projectId===project && i.title.startsWith(imp+' —')) ?? await api('POST',`/companies/${COMPANY}/issues`,{title:`${imp} — ${objective.split('|')[2].trim()}`,description:`CANONICAL IMP PARENT — not a dispatchable work packet.\nSPEC ${spec} v1.1 SHA256 ${hash}\nExecution scope: initial framework/office binding v1.1 on brunode.\nNormative §25.1 row (verbatim):\n${objective}\nNormative §25.2 row (verbatim):\n${dependencies}\nST accepted != IMP accepted. Parent remains unaccepted until §20.2.10 passes and a scoped IMP_RECEIPT exists. No factual/empirical dependency closed by synthetic tests.`,projectId:project,parentId:root.id,projectWorkspaceId:workspace.id,status:'backlog',priority:'high'});
}
function policy(agents){return {mode:'normal',stages:agents.map((id,n)=>({id:randomUUID(),type:'review',participants:[{id:randomUUID(),type:'agent',agentId:id}],approvalsNeeded:1})),commentRequired:true,maxReviewRounds:3};}
const common=`SPEC ID=${spec}; version=1.1; SHA256=${hash}. Project=${project}; workspace=${dir}. Baseline=operations/bootstrap/baseline-manifest.json (non-git workspace); inspect live hashes before writing. Frozen=P1-P7, D1-D5, terminology, economic contracts, review/receipt gates, office routing and budget policy. Native parent is program root for existing controller convention; semantic parent IMP and its issue are recorded below. Reviewers must review existing output, not regenerate an architecture. After ST approval, Command separately evaluates the full parent gate and writes a full scoped IMP_RECEIPT linked to tests/reviews, or records the unmet criteria. Do not close the program root.`;
function packet(imp,cls,obj,scope,paths,sections,outputs,tests,review){return `WORK-PACKET v1\nclass: ${cls}\nobjective: ${obj}\nscope: Packet=WP-${imp}-ST-1-v1.1; Subtask=ST-${imp.slice(4)}.1; Parent=${imp} (${parents[imp].identifier}, ${parents[imp].id}). ${common}\n${scope}\nSource Sections: ${sections}. Required semantic packet fields are contained in these named sections and the linked canonical rows.\nallowed_paths: ${paths}\nprohibited: Canonical docs are read-only. No Alexandria code/issue writes. No commits, push, branches, worktrees, agents/subagents, deploy, purchases, trading, budgets, credentials, services or quota changes. Preserve dirty files. No frozen semantic changes. No broader IMP scope.\ndependencies: REQUIRES=current verified SPEC and corresponding sections. REQUIRES_AUDIT=none. REQUIRES_EVIDENCE=none. Project ON must be verified through API. Outputs below are not prerequisites.\nacceptance: All acceptance criteria in §25.1 for ${imp} must pass in the declared scope. No placeholders as evidence. ${outputs}\ntests: ${tests}\nevidence: Record actual commands/results, input/source hashes, changed-file hashes, boundary cases, baseline and resulting versions, live evidence timestamps; no secret values.\ndone: Complete ST_RECEIPT per §20.2.8 and native review requested; worker completion is only recommended status. Parent remains pending until §20.2.10 and separate IMP_RECEIPT.\nhandoff: Write operations/receipts/${imp}-ST-1.json with packet/subtask/parent identity; worker/model route; starting baseline; resulting content-hash version; inputs used; artifacts; result; tests run and results; evidence; assumptions; deviations; dependency findings; failures/retries; recommended status. Add native continuity-checkpoint document and summary comment. ${review}\nno_guess: Unknown facts remain unknown. Canonical contradictions: stop only branch and record §20.2.12 SPEC_CHANGE_REQUEST. Technical choices preserving semantics are local decisions. Read AGENTS.md.\nreview: ${review}\n`;}
const p25=packet('IMP-25','critical','Auditar el Paperclip real y reconciliar sus capacidades con §20.2.',
'Author role=Opus hard-reasoning auditor, not independent reviewer of this same ST. Read only actual office controller, project switch, queue, instructions, routes, native review, receipt/recovery and systemd. Read-only API via existing pcapi.mjs. Inventory source hashes and current dirty files so concurrent Bru/Claude budget work is preserved. Audit ROOT/refill references to LAT-20, worker cwd/instructions, pendingFinalAcceptance and project-state isolation, Hermes alert path, user linger and timer dependencies. The coordinator temporarily stopped latinosolutions-continuity.timer during the handoff; native Paperclip/awareness remain running. Identify factual gaps and smallest extension surface without implementing IMP-26. Record that active Alexandria review may finish; OFF blocks new work. Baseline code exists at /home/op/.paperclip/integrations/office-continuity, vendored service and /home/op/office-continuity/project-switch. Never print auth/config secrets.',
'operations/audit/IMP-25/**, operations/receipts/IMP-25-ST-1.json',
'§§20.2,24 DEP-27,25.1 IMP-25,25.2 IMP-25',
'Write operations/audit/IMP-25/capability-mapping.md and evidence.json. Contrast ON/OFF, routing, READY, dispatch/recovery, reviews, ST/IMP receipts and continuation. Explicit unknowns and audit scope; identify every required IMP-26 gap with file/line evidence. Accepted audit does not claim missing capability works.',
'Run read-only inspection and relevant non-mutating project-gate/packet tests with /opt/node/bin/node --test project-gate.test.mjs packet.test.mjs in office-continuity; save observed TAP. Verify API project state, project workspace, systemd show timer and user linger; source hashes. Do not run live switch integration tests that toggle Alexandria.',
'Native independent review by Tech Lead Astra. After approval Tech Lead evaluates IMP-25 parent separately; audit may legitimately identify gaps, DEP-27 only factual inspected scope can close.');
const p01=packet('IMP-01','routine','Materializar contratos de identidad, versiones y namespaces de Procurement Research v1.1.',
'Author=DeepSeek routine production. Implement minimal dependency-free identity/version/state/receipt validators and schemas using available Node runtime, with meaningful negative tests. Read the normative SPEC §§0-3,13-14 in full plus parent rows. Namespace collisions q_t (sentiment vs quantity), A0/A1 (ablation vs autonomy), S1-S5 Strategy vs historical workstream must be rejected or represented by explicit discriminated namespaces. Keep concept maturity, run data/validity/coverage/source statuses, research verdict, governance event and receipt namespaces separate. Validate required economic bundle identities/versions and unknown required economic fields with reason preservation; do not invent numeric defaults. Bounded support only: no evaluator, financial algorithms or external packages. Include all engineering WORK-PACKET/ST_RECEIPT/IMP_RECEIPT identity/version linkage. Choose exact serialization as implementation detail; derive fields from SPEC, no historical reconstruction.',
'src/contracts/**, test/contracts/**, operations/receipts/IMP-01-ST-1.json, operations/audit/IMP-01/**',
'§§0-3,13-14; §20.2.7-.10; §25.1/25.2 IMP-01',
'Runnable validators/schemas, examples explicitly synthetic, negative tests for namespace ambiguity, missing versions/required fields and preservation of unavailable reasons. Receipt describes exact scope and limitations; tests demonstrate rejection rather than silently populating fields.',
'Run /opt/node/bin/node --test test/contracts/*.test.mjs from canonical workspace. Include independently chosen valid and invalid cases that cover every parent acceptance criterion, and hash outputs; no market runs.',
'Native stage 1 Independent Reviewer Opus, stage 2 Tech Lead Astra. Reviewers must independently run tests and verify canonical coverage. Tech Lead then separately evaluates IMP-01 parent acceptance and records IMP_RECEIPT.');
const children={};
for(const [imp,description,reviews] of [['IMP-25',p25,[command]],['IMP-01',p01,[reviewer,command]]]){
 fs.writeFileSync(`${dir}/operations/packets/${imp}-ST-1.md`,description);
 children[imp]=existing.find(i=>i.projectId===project && i.title.startsWith(`[READY] ${imp} /`)) ?? await api('POST',`/companies/${COMPANY}/issues`,{title:`[READY] ${imp} / ST-${imp.slice(4)}.1 — ${imp==='IMP-25'?'audit factual Paperclip':'contratos de identidad y namespaces'}`,description,projectId:project,parentId:root.id,projectWorkspaceId:workspace.id,status:'backlog',priority:'high',executionPolicy:policy(reviews),assigneeAdapterOverrides:{adapterConfig:{cwd:dir}}});
}
const state={project,workspaceId:workspace.id,root:{id:root.id,identifier:root.identifier},parents:Object.fromEntries(Object.entries(parents).map(([k,v])=>[k,{id:v.id,identifier:v.identifier}])),children:Object.fromEntries(Object.entries(children).map(([k,v])=>[k,{id:v.id,identifier:v.identifier}]))};
fs.writeFileSync(dir+'/operations/bootstrap/paperclip-ids.json',JSON.stringify(state,null,2)+'\n');
console.log(JSON.stringify(state));
console.log(await api('POST',`/projects/${project}/execution`,{state:'on'}));
console.log(await api('GET',`/companies/${COMPANY}/projects/execution`));
// Bootstrap dispatch is explicit Director action through existing native office API while binding is unimplemented.
// Resume only the Command lane reported OPEN and paused by the existing controller.
const ctl=JSON.parse(fs.readFileSync('/home/op/.paperclip/integrations/office-continuity/controller-state.json','utf8'));
const a=await api('GET',`/agents/${command}`);
if(a.status==='paused' && ctl.pausedByController?.[command]){await api('POST',`/agents/${command}/resume`,{}); console.log('Command resumed within existing OPEN lane');}
for(const [imp,agent] of [['IMP-01',worker],['IMP-25',reviewer]]){
 const issue=await api('PATCH',`/issues/${children[imp].id}`,{status:'todo',assigneeAgentId:agent,comment:'Owner-authorized Energy Markets bootstrap. Director dispatch through native Paperclip under current OPEN lane; automated timer temporarily held to prevent wrong Alexandria refill. WORK-PACKET and native review gates apply. No parent acceptance inferred.'});
 console.log(JSON.stringify({dispatched:issue.identifier,assignee:issue.assigneeAgentId,status:issue.status}));
}
